### ISSUE TITLE
android.view.InflateException error

### ISSUE THREAD

**Issue by chihacker** [nirhart/ParallaxScroll#30]
android.view.InflateException: Binary XML file line #19: Error inflating class com.nirhart.parallaxscroll.views.ParallaxListView
            at android.view.LayoutInflater.createView(LayoutInflater.java:620)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at com.hoit.coupli.fragment.MainFragment.setLayout(MainFragment.java:232)
            at com.hoit.coupli.fragment.MainFragment.onCreateView(MainFragment.java:211)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:938)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1115)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:478)
            at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1068)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:914)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1436)
            at android.view.View.measure(View.java:16659)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5166)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1415)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:706)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:599)
            at android.view.View.measure(View.java:16659)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5166)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:16659)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5166)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1415)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:706)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:599)
            at android.view.View.measure(View.java:16659)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5166)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2536)
            at android.view.View.measure(View.java:16659)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2078)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1234)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1416)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1121)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6030)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:544)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5094)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflat

I use gradle complie 'com.github.nirhart:parallaxscroll:1.0'

**Comment by EboMike** [comment]
I'm getting the same thing when I try it on an AVD with Android 2.3 or below.

Seems like it's using setAlpha() and other Honeycomb-specific functions without checking isAPI11 first.

Here is more context:

I/dalvikvm﹕ Could not find method android.view.View.setAlpha, referenced from method com.nirhart.parallaxscroll.views.ParallaxedView.setAlpha
W/dalvikvm﹕ VFY: unable to resolve virtual method 11602: Landroid/view/View;.setAlpha (F)V
D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x000e
I/dalvikvm﹕ Could not find method android.view.View.setTranslationY, referenced from method com.nirhart.parallaxscroll.views.ParallaxedView.setOffset
W/dalvikvm﹕ VFY: unable to resolve virtual method 11644: Landroid/view/View;.setTranslationY (F)V
D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x000e

(This immediately preceeds the stack trace about the failed layout inflation.)
